// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjWHQuqAkrX2JJH1Xn2TPWgDntycmCeLA',
    appId: '1:572479542698:web:d342906721657e6e3d07d3',
    messagingSenderId: '572479542698',
    projectId: 'appdomotica-7e915',
    authDomain: 'appdomotica-7e915.firebaseapp.com',
    storageBucket: 'appdomotica-7e915.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVpCD2GWI2DexxL68tRBmr70zo9gmSHv0',
    appId: '1:572479542698:android:d001ee69da7155d83d07d3',
    messagingSenderId: '572479542698',
    projectId: 'appdomotica-7e915',
    storageBucket: 'appdomotica-7e915.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5sn4SPJUOFHUxlgZtcRyK4Di5DyuJ-zc',
    appId: '1:572479542698:ios:5c37318059ad99273d07d3',
    messagingSenderId: '572479542698',
    projectId: 'appdomotica-7e915',
    storageBucket: 'appdomotica-7e915.appspot.com',
    iosBundleId: 'com.example.appdomotica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5sn4SPJUOFHUxlgZtcRyK4Di5DyuJ-zc',
    appId: '1:572479542698:ios:0b272e9a671036e43d07d3',
    messagingSenderId: '572479542698',
    projectId: 'appdomotica-7e915',
    storageBucket: 'appdomotica-7e915.appspot.com',
    iosBundleId: 'com.example.appdomotica.RunnerTests',
  );
}
